name: CI

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  ci:
    runs-on: windows-2022
    steps:
    - name: Setup dotnet
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' 
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: microsoft
    - name: Setup SonarQube
      uses: warchant/setup-sonar-scanner@v7
    - uses: actions/checkout@v4
    - name: Scan
      shell: pwsh
      run: |
        sonar-scanner.bat `
        -D sonar.projectKey=$env:PROJECT_NAME `
        -D sonar.organization=$env:SONAR_ORG `
        -D sonar.projectVersion=$env:APP_VERSION `
        -D sonar.projectBaseDir=$env:GITHUB_WORKSPACE `
        -D sonar.sources=$env:GITHUB_WORKSPACE/demo_flask `
        -D sonar.scanner.metadataFilePath=$env:GITHUB_WORKSPACE/report-task.txt `
        -D sonar.python.version=3.9
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        PROJECT_NAME: 'kostakoff_python3-demo-project'
        SONAR_ORG: 'kostakoff'
        SONAR_HOST_URL: 'https://sonarcloud.io'
